Update kakrc
update zellij module

diff --git a/configs/kak/kakrc b/configs/kak/kakrc
--- a/configs/kak/kakrc
+++ b/configs/kak/kakrc
@@ -51,13 +51,13 @@ define-command window-edit-match -docstring "Open all files matching giving patt
 }}
 complete-command window-edit-match shell-script-candidates %{ fd -tf . . }
 define-command find -docstring "find files" -params .. %{
-    set global zellij_run_options "-c -d down"
+    set window zellij_run_options "-c -d down"
     terminal fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} edit '$f'\n"""\; done | kak -p %val{session}
 }
 complete-command find shell-script-candidates %{ fd -tf . . }
 define-command window-find -docstring "find files in other windows" -params .. %{
-    set global zellij_run_options "-c -d down"
-    terminal fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} set global zellij_run_options '-c'; new edit '$f'\n"""\; done | kak -p %val{session}
+    set window zellij_run_options "-c -d down"
+    terminal fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} new edit '$f'\n"""\; done | kak -p %val{session}
 }
 complete-command window-find shell-script-candidates %{ fd -tf . . }
 
@@ -75,7 +75,7 @@ map global user W %{:window-edit-match } -docstring "Find files in windows"
 map global user / %{:grep } -docstring "Grep"
 map global user < %{:fifo } -docstring "Shell"
 map global user : %{:terminal } -docstring "Terminal"
-map global user s %{:window-edit<ret>} -docstring "Split window"
+map global user s %{:new edit!<ret>} -docstring "Split window"
 
 # System clipboard handling
 # ─────────────────────────
@@ -112,31 +112,24 @@ provide-module zellij %{
 
 # ensure we're running under zellij
 evaluate-commands %sh{
-    [ -z "${client_opt_windowing_modules}" ] || [ -n "$ZELLIJ" ] || echo 'fail zellij not detected'
+    [ -z "${kak_opt_windowing_modules}" ] || [ -n "$ZELLIJ" ] || echo 'fail zellij not detected'
 }
 
-declare-option -hidden -docstring %{zellij run options (
-    -c, --close-on-exit            Close the pane immediately when its command exits
-        --cwd <CWD>                Change the working directory of the new pane
-    -d, --direction <DIRECTION>    Direction to open the new pane in
-    -f, --floating                 Open the new pane in floating mode
-    -h, --help                     Print help information
-    -n, --name <NAME>              Name of the new pane
-    -s, --start-suspended          Start the command suspended, only running after you first presses ENTER)}\
+declare-option -hidden -docstring %{zellij run options (please check out "zellij run --help" for detail)}\
     str zellij_run_options ""
-declare-option -hidden -docstring %{zellij run command} str zellij_run_cmd ""
 
-define-command -hidden -params 0 zellij-run %{
+define-command -hidden -params .. zellij-run %{
     nop %sh{
-    zellij run ${kak_opt_zellij_run_options} -- $SHELL -i -c "${kak_opt_zellij_run_cmd}" < /dev/null > /tmp/zellij.log 2>&1 &
+        zellij run ${kak_opt_zellij_run_options} -- $SHELL -i -c "$*" < /dev/null > /dev/null 2>&1 &
     }
     set global zellij_run_options ""
-    set global zellij_run_cmd ""
+    unset buffer zellij_run_options
+    unset window zellij_run_options
 }
 
 define-command -hidden -params 1.. zellij-terminal-impl %{
-    set global zellij_run_cmd "%arg{@}"
-    zellij-run
+    set global zellij_run_options "--close-on-exit"
+    zellij-run %arg{@}
 }
 complete-command zellij-terminal-impl shell
 
@@ -146,8 +139,7 @@ The current pane is split into two, top and bottom
 The program passed as argument will be executed in the new terminal' \
 %{
     set global zellij_run_options "--direction down"
-    set global zellij_run_cmd "%arg{@}"
-    zellij-run
+    zellij-run %arg{@}
 }
 complete-command zellij-terminal-vertical shell
 
@@ -157,22 +149,34 @@ The current pane is split into two, left and right
 The program passed as argument will be executed in the new terminal' \
 %{
     set global zellij_run_options "--direction right"
-    set global zellij_run_cmd "%arg{@}"
-    zellij-run
+    zellij-run %arg{@}
 }
 complete-command zellij-terminal-horizontal shell
 
-define-command zellij-focus -params 0 -docstring '
-zellij-focus: focus a panel' \
+define-command zellij-focus -params ..1 -docstring '
+zellij-focus [<client>]: focus the given client
+If no client is passed then the current one is used' \
 %{ nop %sh{
-    zellij action switch-mode pane
+    if [ $# -eq 1 ]; then
+        output=$(mktemp -d "${TMPDIR:-/tmp}"/kak-zellij.XXXXXXXX)/dump-screen
+        pane_count=0
+        while [ $((pane_count+=1)) -lt 10 ]; do
+             if zellij action dump-screen "$output" && grep "$1@\[$kak_session\]" "$output" ; then
+                 break;
+             fi
+             zellij action focus-next-pane
+        done
+        rm -r $(dirname $output)
+    fi
 }}
+complete-command -menu zellij-focus client
 
 ## The default behaviour for the `new` command is to open an horizontal pane in a zellij session
 alias global focus zellij-focus
 alias global terminal zellij-terminal-impl
 
 }
+
 evaluate-commands %sh{
     if [ -n "$ZELLIJ" ]; then
         printf 'require-module zellij'
