Update kakrc

diff --git a/configs/kak/kakrc b/configs/kak/kakrc
--- a/configs/kak/kakrc
+++ b/configs/kak/kakrc
@@ -29,7 +29,7 @@ define-command -params .. fifo %{ evaluate-commands %sh{
 }}
 complete-command fifo shell
 define-command shell -docstring "Run commands in a ternimal shell" -params 1.. %{
-    terminal %val{client_env_SHELL} -i -c "%arg{@}"
+    zellij-run "-c -d down"  %val{client_env_SHELL} -i -c "%arg{@}"
 }
 complete-command shell shell
 define-command delete-buffers-match -docstring "Delete all buffers matching giving pattern" -params 1 %{ evaluate-commands %sh{
@@ -55,12 +55,10 @@ define-command window-edit-match -docstring "Open all files matching giving patt
 }}
 complete-command window-edit-match shell-script-candidates %{ fd -tf . . }
 define-command find -docstring "find files" -params .. %{
-    set window zellij_run_options "-c -d down"
     shell fd -tf %arg{@} | sk -m | while read f\; do echo eval -client %val{client} edit """$f""" \; done | kak -p %val{session}
 }
 complete-command find shell-script-candidates %{ fd -tf . . }
 define-command window-find -docstring "find files in other windows" -params .. %{
-    set window zellij_run_options "-c -d down"
     shell fd -tf %arg{@} | sk -m | while read f\; do echo eval -client %val{client} new edit """$f""" \; done | kak -p %val{session}
 }
 complete-command window-find shell-script-candidates %{ fd -tf . . }
@@ -116,24 +114,17 @@ provide-module zellij %{
 
 # ensure we're running under zellij
 evaluate-commands %sh{
-    [ -z "${kak_opt_windowing_modules}" ] || [ -n "$ZELLIJ" ] || echo 'fail zellij not detected'
+    [ -z "${kak_opt_windowing_modules}" ] || [ -n "$ZELLIJ" -a -n "$ZELLIJ_SESSION_NAME" ] || echo 'fail zellij not detected'
 }
 
-declare-option -hidden -docstring %{zellij run options (please check out "zellij run --help" for detail)}\
-    str zellij_run_options ""
-
-define-command -hidden -params .. zellij-run %{
-    nop %sh{
-        zellij run $kak_opt_zellij_run_options -- "$@"
-    }
-    set global zellij_run_options ""
-    unset buffer zellij_run_options
-    unset window zellij_run_options
-}
+define-command -hidden -params 2.. zellij-run %{ nop %sh{
+    zellij_run_options=$1
+    shift
+    zellij --session "$kak_client_env_ZELLIJ_SESSION_NAME" run $zellij_run_options -- "$@"
+}}
 
 define-command -hidden -params 1.. zellij-terminal-impl %{
-    set global zellij_run_options "--close-on-exit"
-    zellij-run %arg{@}
+    zellij-run "--close-on-exit" %arg{@}
 }
 complete-command zellij-terminal-impl shell
 
@@ -142,8 +133,7 @@ zellij-terminal-vertical <program> [<arguments>]: create a new terminal as a zel
 The current pane is split into two, top and bottom
 The program passed as argument will be executed in the new terminal' \
 %{
-    set global zellij_run_options "--direction down"
-    zellij-run %arg{@}
+    zellij-run "--direction down" %arg{@}
 }
 complete-command zellij-terminal-vertical shell
 
@@ -152,8 +142,7 @@ zellij-terminal-horizontal <program> [<arguments>]: create a new terminal as a z
 The current pane is split into two, left and right
 The program passed as argument will be executed in the new terminal' \
 %{
-    set global zellij_run_options "--direction right"
-    zellij-run %arg{@}
+    zellij-run "--direction right" %arg{@}
 }
 complete-command zellij-terminal-horizontal shell
 
@@ -182,6 +171,7 @@ alias global focus zellij-focus
 alias global terminal zellij-terminal-impl
 
 }
+
 
 evaluate-commands %sh{
     if [ -n "$ZELLIJ" ]; then
