Update kakrc
remove autoload dir

diff --git a/configs/kak/kakrc b/configs/kak/kakrc
--- a/configs/kak/kakrc
+++ b/configs/kak/kakrc
@@ -6,7 +6,7 @@ add-highlighter global/ show-matching
 add-highlighter global/ regex \h+$ 0:Error
 
 set-option global tabstop 4
-# set-option global grepcmd 'rg --column'
+set-option global grepcmd 'rg --column'
 
 colorscheme gruvbox-dark
 
@@ -41,7 +41,6 @@ define-command edit-match -docstring "Open all files matching giving pattern" -p
     done
 }}
 complete-command edit-match file
-require-module zellij
 define-command window-edit-match -docstring "Open all files matching giving pattern in windows" -params .. %{ evaluate-commands %sh{
     fd $@ | while read f; do
         printf "window-edit '$f'\n"
@@ -95,4 +94,75 @@ evaluate-commands %sh{
     printf "map global user -docstring 'yank to clipboard' Y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to %s clipboard}<ret>'\n" "$copy -selection clipboard" "$backend"
     printf "map global user -docstring 'replace from clipboard' R '|%s<ret>'\n" "$paste"
     printf "define-command -override echo-to-clipboard -params .. %%{ echo -to-shell-script '%s' -- %%arg{@} }" "$copy"
+}
+
+# https://zellij.dev/
+# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
+
+provide-module zellij %{
+
+# ensure we're running under zellij
+evaluate-commands %sh{
+    [ -z "${kak_opt_windowing_modules}" ] || [ -n "$ZELLIJ" ] || echo 'fail zellij not detected'
+}
+
+define-command -hidden -params 2.. zellij %{
+    evaluate-commands %sh{
+       zellij "$@" < /dev/null > /dev/null 2>&1 &
+    }
+}
+
+define-command -hidden -params 1.. zellij-terminal-impl %{
+   zellij run %arg{@}
+}
+
+define-command zellij-terminal-vertical -params 1.. -docstring '
+zellij-terminal-vertical <program> [<arguments>]: create a new terminal as a zellij pane
+The current pane is split into two, top and bottom
+The program passed as argument will be executed in the new terminal' \
+%{
+    zellij-terminal-impl -d down -- %arg{@}
+}
+complete-command zellij-terminal-vertical shell
+
+define-command zellij-terminal-horizontal -params 1.. -docstring '
+zellij-terminal-horizontal <program> [<arguments>]: create a new terminal as a zellij pane
+The current pane is split into two, left and right
+The program passed as argument will be executed in the new terminal' \
+%{
+    zellij-terminal-impl -d right -- %arg{@}
+}
+complete-command zellij-terminal-horizontal shell
+
+define-command zellij-terminal-window -params 1.. -docstring '
+zellij-terminal-window <program> [<arguments>] [<arguments>]: create a new terminal as a zellij window
+The program passed as argument will be executed in the new terminal' \
+%{
+    zellij-terminal-impl -- %arg{@}
+}
+complete-command zellij-terminal-window shell
+
+define-command zellij-terminal-window-edit -params .. -docstring '
+zellij-terminal-window-edit <file>: create a new window to edit given file' \
+%{
+    zellij-terminal-impl -c -- kak -c %val{session} %arg{@}
+}
+complete-command zellij-terminal-window-edit file
+
+define-command zellij-focus -params 0 -docstring '
+zellij-focus: focus a panel' \
+%{
+    zellij action switch-mode pane
+}
+
+## The default behaviour for the `new` command is to open an horizontal pane in a zellij session
+alias global focus zellij-focus
+alias global terminal zellij-terminal-window
+alias global window-edit zellij-terminal-window-edit
+
+}
+evaluate-commands %sh{
+    if [ -n "$ZELLIJ" ]; then
+		printf 'require-module zellij'
+    fi
 }
