Update kakrc
update zellij module

diff --git a/configs/kak/kakrc b/configs/kak/kakrc
--- a/configs/kak/kakrc
+++ b/configs/kak/kakrc
@@ -15,14 +15,14 @@ hook global WinSetOption filetype=kotlin %[
     set-option window lintcmd './abt -v build check'
 ]
 
-define-command mkdir -docstring "" -params .. %{ echo %sh{ mkdir -pv ${@-$(dirname $kak_buffile)} } }
+define-command mkdir -docstring "" -params .. %{ echo %sh{ mkdir -pv ${@-$(dirname $client_buffile)} } }
 # Shortcut to quickly exit the editor
 define-command -docstring "save and quit" x "write-all; quit"
 define-command -params .. fifo %{ evaluate-commands %sh{
     output=$(mktemp -d "${TMPDIR:-/tmp}"/kak-fifo.XXXXXXXX)/fifo
     mkfifo ${output}
     ( eval "$@" > ${output} 2>&1 & ) > /dev/null 2>&1 < /dev/null
-    printf %s\\n "evaluate-commands -try-client '$kak_opt_toolsclient' %{
+    printf %s\\n "evaluate-commands -try-client '$client_opt_toolsclient' %{
         edit! -fifo ${output} *fifo*
         hook -always -once buffer BufCloseFifo .* %{ nop %sh{ rm -r $(dirname ${output}) } }
     }"
@@ -30,7 +30,7 @@ define-command -params .. fifo %{ evaluate-commands %sh{
 complete-command fifo shell
 define-command delete-buffers-match -docstring "Delete all buffers matching giving pattern" -params 1 %{ evaluate-commands %sh{
     pattern=$1
-    eval "set -- $kak_buflist"
+    eval "set -- $client_buflist"
     for buf in "$@"; do
         printf "%s\n" "$buf"
     done | rg $pattern - | while read f; do
@@ -46,16 +46,18 @@ define-command edit-match -docstring "Open all files matching giving pattern" -p
 complete-command edit-match shell-script-candidates %{ fd -tf . . }
 define-command window-edit-match -docstring "Open all files matching giving pattern in windows" -params .. %{ evaluate-commands %sh{
     fd $@ | while read f; do
-        printf "window-edit '$f'\n"
+        printf "new edit '$f'\n"
     done
 }}
 complete-command window-edit-match shell-script-candidates %{ fd -tf . . }
 define-command find -docstring "find files" -params .. %{
-    terminal -c -d down fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} edit $f\n"""\; done | kak -p %val{session}
+    set global zellij_run_options "-c -d down"
+    terminal fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} edit '$f'\n"""\; done | kak -p %val{session}
 }
 complete-command find shell-script-candidates %{ fd -tf . . }
 define-command window-find -docstring "find files in other windows" -params .. %{
-    terminal -c -d down fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} window-edit $f\n"""\; done | kak -p %val{session}
+    set global zellij_run_options "-c -d down"
+    terminal fd -tf %arg{@} | sk -m | while read f\; do printf """eval -client %val{client} set global zellij_run_options '-c'; new edit '$f'\n"""\; done | kak -p %val{session}
 }
 complete-command window-find shell-script-candidates %{ fd -tf . . }
 
@@ -80,7 +82,7 @@ map global user s %{:window-edit<ret>} -docstring "Split window"
 
 evaluate-commands %sh{
     if [ -n "$SSH_TTY" ]; then
-        copy='printf "\033]52;;%s\033\\" $(base64 | tr -d "\n") > $( [ -n "$kak_client_pid" ] && echo /proc/$kak_client_pid/fd/0 || echo /dev/tty )'
+        copy='printf "\033]52;;%s\033\\" $(base64 | tr -d "\n") > $( [ -n "$client_client_pid" ] && echo /proc/$client_client_pid/fd/0 || echo /dev/tty )'
         paste='printf "paste unsupported through ssh"'
         backend="OSC 52"
     else
@@ -110,33 +112,32 @@ provide-module zellij %{
 
 # ensure we're running under zellij
 evaluate-commands %sh{
-    [ -z "${kak_opt_windowing_modules}" ] || [ -n "$ZELLIJ" ] || echo 'fail zellij not detected'
+    [ -z "${client_opt_windowing_modules}" ] || [ -n "$ZELLIJ" ] || echo 'fail zellij not detected'
 }
 
-define-command -hidden -params 2.. zellij %{
-    evaluate-commands %sh{
-       zellij "$@" < /dev/null > /dev/null 2>&1 &
+declare-option -hidden -docstring %{zellij run options (
+    -c, --close-on-exit            Close the pane immediately when its command exits
+        --cwd <CWD>                Change the working directory of the new pane
+    -d, --direction <DIRECTION>    Direction to open the new pane in
+    -f, --floating                 Open the new pane in floating mode
+    -h, --help                     Print help information
+    -n, --name <NAME>              Name of the new pane
+    -s, --start-suspended          Start the command suspended, only running after you first presses ENTER)}\
+    str zellij_run_options ""
+declare-option -hidden -docstring %{zellij run command} str zellij_run_cmd ""
+
+define-command -hidden -params 0 zellij-run %{
+    nop %sh{
+    zellij run ${kak_opt_zellij_run_options} -- $SHELL -i -c "${kak_opt_zellij_run_cmd}" < /dev/null > /tmp/zellij.log 2>&1 &
     }
+    set global zellij_run_options ""
+    set global zellij_run_cmd ""
 }
-define-command -hidden -params 1.. zellij-terminal-impl %{ evaluate-commands %sh{
-   arg_count=0
-   i=1
-   while [ $i -lt $# ]; do
-       a=${@:$i:1}
-       if [ "${a:0:1}" = "-" ]; then
-           if [ "${a:1:1}" = "d" -o "${a:1:1}" = "n" ]; then
-               ((i+=2))
-           else
-               ((i+=1))
-           fi
-           arg_count=$((i-1))
-       else
-           arg_count=$((i-1))
-           i=$#
-       fi
-   done
-   echo zellij run ${@:1:$arg_count} -- $SHELL -i -c "'"${@:$((1+$arg_count))}"'"
-}}
+
+define-command -hidden -params 1.. zellij-terminal-impl %{
+    set global zellij_run_cmd "%arg{@}"
+    zellij-run
+}
 complete-command zellij-terminal-impl shell
 
 define-command zellij-terminal-vertical -params 1.. -docstring '
@@ -144,7 +145,9 @@ zellij-terminal-vertical <program> [<arguments>]: create a new terminal as a zel
 The current pane is split into two, top and bottom
 The program passed as argument will be executed in the new terminal' \
 %{
-    zellij-terminal-impl -d down %arg{@}
+    set global zellij_run_options "--direction down"
+    set global zellij_run_cmd "%arg{@}"
+    zellij-run
 }
 complete-command zellij-terminal-vertical shell
 
@@ -153,27 +156,21 @@ zellij-terminal-horizontal <program> [<arguments>]: create a new terminal as a z
 The current pane is split into two, left and right
 The program passed as argument will be executed in the new terminal' \
 %{
-    zellij-terminal-impl -d right %arg{@}
+    set global zellij_run_options "--direction right"
+    set global zellij_run_cmd "%arg{@}"
+    zellij-run
 }
 complete-command zellij-terminal-horizontal shell
 
-define-command zellij-terminal-window-edit -params .. -docstring '
-zellij-terminal-window-edit <file>: create a new window to edit given file' \
-%{
-    zellij-terminal-impl -c kak -c %val{session} %arg{@}
-}
-complete-command zellij-terminal-window-edit file
-
 define-command zellij-focus -params 0 -docstring '
 zellij-focus: focus a panel' \
-%{
+%{ nop %sh{
     zellij action switch-mode pane
-}
+}}
 
 ## The default behaviour for the `new` command is to open an horizontal pane in a zellij session
 alias global focus zellij-focus
 alias global terminal zellij-terminal-impl
-alias global window-edit zellij-terminal-window-edit
 
 }
 evaluate-commands %sh{
